### ISSUE TITLE
Create a view that lists issues as a table

### ISSUE THREAD

**Issue by JGefroh** [space-turtles/issue-tracker#2]
We'll want a view that lists issues in table form. For now it can list fake data (or no data at all).

It should be attached to a route (eg. accessible by going to `/issues` or whatever is appropriate).

**Comment by venerated** [comment]
Do all routes go into the app.js file or in their individual component file?

**Comment by JGefroh** [comment]
For this project the routes will be defined on a per-module basis - the routes for a module will go into the `<module>-module.js` files.
